### ISSUE TITLE
Lifetime Limit in specified days

### ISSUE THREAD

**Issue by jan5650** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#177]
Welcome!

Is it possible to make my device work only for 10 days?

Since the device is GPS based and uses your library, is there a way for me to enter today's date in the software, retrieve the current date from the satellites when GPS is connected, and if there is a 10 day difference between the two, limit the operation.

If so, how can I solve it?

Thank you!

**Comment by PaulZC** [comment]
Hi @jan5650 ,

Please have a look at ```getUnixEpoch()``` in [this example](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/blob/main/examples/Example24_GetUnixEpochAndMicros/Example24_GetUnixEpochAndMicros.ino). It returns the GNSS time and date as Unix Epoch, i.e. the number of seconds since January 1st 1970. If you include the time and date as Unix Epoch in your code, a simple subtraction will tell you the time difference (in seconds).

Best wishes,
Paul
