### ISSUE TITLE
Examples display incorrect fractional lat/long

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#19]
If the lat_frac has leading zeros, they are dropped, leading to the incorrect value being printed:

![image](https://user-images.githubusercontent.com/117102/113174155-54333300-9207-11eb-8977-7a54688f88f2.png)

I know examples 10 and 11 are effected but there may be others:

![image](https://user-images.githubusercontent.com/117102/113174037-3960be80-9207-11eb-8ea9-a1b53f98c9d8.png)

![image](https://user-images.githubusercontent.com/117102/113173958-28b04880-9207-11eb-98d2-1fa637be3758.png)

One solution is to use printf

  Serial.printf("%d.%07d\n", lat_int, lat_frac); // Print the integer part of the latitude

But I know its support is iffy. We might have to break down and just write a silly helper function inside these examples.

**Comment by PaulZC** [comment]
Fixed in [this commit](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/commit/e483b119cc254833419d528c9b23c520475d2dbc).
I've searched, and I think this is one of a kind...
A couple of examples weren't using nanoseconds correctly (nanoseconds can be negative) so I've corrected those too, but that's a different issue.

**Comment by PaulZC** [comment]
I think this doesn't actually affect Example11 as the printing there is done all in one go?
